#!/usr/bin/env python3
"""Collect license notices for the locked Rust build/runtime dependency graph."""
import json
from pathlib import Path
import subprocess
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
metadata = json.loads(subprocess.check_output([
    'cargo', '+1.97.1', 'metadata', '--locked', '--format-version=1',
    '--manifest-path', str(ROOT / 'rust/Cargo.toml'),
], text=True))
packages = {p['id']: p for p in metadata['packages']}
nodes = {n['id']: n for n in metadata['resolve']['nodes']}
selected = set()
def visit(id):
    if id in selected:
        return
    selected.add(id)
    for dep in nodes[id]['deps']:
        if any(k['kind'] != 'dev' for k in dep['dep_kinds']):
            visit(dep['pkg'])
visit(metadata['resolve']['root'])
cache = {}
def remote(repository, revision, name):
    url = f'https://raw.githubusercontent.com/{repository}/{revision}/{name}'
    if url not in cache:
        with urllib.request.urlopen(url) as response:
            cache[url] = response.read().decode()
    return url, cache[url]

out = ['# Native artifact third-party notices\n',
       'Generated by `tool/generate_native_notices.py` from locked Cargo metadata.\n'
       'Includes build-time dependencies and all platform variants (a superset of any single binary).\n'
       'SNE itself is covered by the package LICENSE. GTK/GDK are system dependencies, not bundled.\n']
for p in sorted((packages[id] for id in selected), key=lambda p: (p['name'], p['version'])):
    if p['id'] == metadata['resolve']['root']:
        continue
    directory = Path(p['manifest_path']).parent
    notices = [(f.name, f.read_text(errors='replace')) for f in sorted(directory.iterdir())
               if f.is_file() and f.name.upper().startswith(('LICENSE', 'COPYING', 'NOTICE', 'COPYRIGHT'))]
    if not notices:
        if p['repository'] == 'https://github.com/madsmtm/objc2':
            revision = json.loads((directory / '.cargo_vcs_info.json').read_text())['git']['sha1']
            notices = [remote('madsmtm/objc2', revision, 'LICENSE.txt')]
        elif p['name'] == 'dispatch':
            revision = json.loads((directory / '.cargo_vcs_info.json').read_text())['git']['sha1']
            # This published crate and its source tree have no license file;
            # retain its authors and MIT declaration with the standard terms.
            notices = [('Cargo.toml MIT declaration (no separate license file)',
                        'Authors: ' + ', '.join(p['authors']) + '\nSource revision: ' + revision + '\n\n' +
                        (ROOT / 'LICENSE').read_text().split('MIT LICENSE', 1)[1].strip())]
        elif p['name'].startswith('winapi-'):
            winapi = next(x for x in packages.values() if x['name'] == 'winapi')
            notices = [(f.name, f.read_text()) for f in sorted(Path(winapi['manifest_path']).parent.glob('LICENSE*'))]
        else:
            raise RuntimeError('Missing license text: ' + p['name'])
    out.append(f"\n## {p['name']} {p['version']}\n\nLicense: {p['license']}\n\nSource: {p['source']}\n\nRepository: {p['repository']}\n")
    for name, text in notices:
        out.append(f'\n### {name}\n\n```text\n{text.rstrip()}\n```\n')
(ROOT / 'native_artifacts/THIRD_PARTY_NOTICES.md').write_text(''.join(out))
print('Wrote notices for', len(selected) - 1, 'locked crates')
